### ISSUE TITLE
Elasticsearch cluster name should include environment name

### ISSUE THREAD

**Issue by kolomiets** [kolomiets/quickstart-jaeger#4]
In order to support multiple Jaeger instances deployed side by side, Elasticsearch cluster name should include `EnvironmentName` provided as Quick Start parameter - similar to the approach for Prometheus workspace:

```
  APSWorkspace:
    Type: AWS::APS::Workspace
    Properties:
      Alias: !Sub jaeger-${EnvironmentName}-workspace
```
